import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
// components

import Hero from "../components/home/hero";
import Objective from "../components/home/objective";
import Partners from "../components/home/partners";
import Services from "../components/home/services";
import Tech from "../components/home/tech";
import Testimonial from "../components/home/testimonial";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Mindev Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mbg.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <div className="hero">
        <Hero />
        <Services />
        <Objective />
        <Tech />
        <Partners />
        <Testimonial />
      </div>
    </div>
  );
};

export default Home;
