import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
// components

import Hero from "../components/home/hero";
import Services from "../components/home/services";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Mindev Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mbg.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <Hero />
      <Services />
    </div>
  );
};

export default Home;
